name = "Perfusion"
uuid = "f2c4f5d8-8176-4777-9c43-b2c4f12bfc82"
authors = ["Zaki A"]
version = "0.1.0"

[compat]
julia = "1.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
